# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RequestClousure4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RequestClousure4
    pod 'Alamofire'
    pod 'SDWebImage'
  target 'RequestClousure4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RequestClousure4UITests' do
    # Pods for testing
  end

end
